name: Node Docker CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Builder Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.1.4
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm run test:unit
      - name: Build
        run: pnpm build && cp package.json pnpm-lock.yaml build/ && cd build/ && pnpm install --frozen-lockfile
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sqooid/mas:latest
          context: ./
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=sqooid/mas:latest
          cache-to: type=inline

      - name: Connect wireguard
        uses: NexRX/WireGuard-Session@v1
        with:
          wg-client-b64: ${{ secrets.WG_CLIENT_B64 }}
          timeout-address: ${{ secrets.WG_HOST_ADDRESS }}
      - name: Deploy
        env:
          KEY: ${{ secrets.SSH_SECRET_KEY }}
          USER: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.WG_HOST_ADDRESS }}
          COMMAND: ${{ secrets.DEPLOY_COMMAND }}
        run: |
          echo "$KEY" > key
          ssh -i key $USER@$HOST " $COMMAND "












          
